name: netinhoappclinica
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.8.4
  firebase_core: ^2.15.0
  firebase_database: ^10.2.4
  firebase_remote_config: ^4.2.4
  firebase_storage: ^11.2.5
  firebase_auth: ^4.6.1
  get_it: ^7.6.0
  go_router: ^10.0.0
  injectable: ^2.1.2
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  collection: ^1.17.0
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1
  google_fonts: ^4.0.4
  shared_preferences: ^2.1.1
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  equatable: ^2.0.5
  formz: ^0.6.0
  intl: ^0.17.0
  mask_text_input_formatter: 2.3.0
  image_picker: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.6
  
scripts:
  brb: "flutter pub run build_runner build --delete-conflicting-outputs"
  brw: "flutter pub run build_runner watch --delete-conflicting-outputs"
  brb_src: "flutter pub run build_runner build --delete-conflicting-outputs --build-filter='lib/src/**.dart'"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
    - family: ClinicaIcons
      fonts:
        - asset: assets/icons/fonts/ClinicaIcons.ttf



 # To run build runner in a specific folder and reduce processing time, use:
 # flutter pub run build_runner build --delete-conflicting-outputs --build-filter='lib/src/<folder_namer>**.dart 