name: netinhoappclinica
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.8.4
  firebase_core: ^2.15.0
  firebase_database: ^10.2.4
  firebase_remote_config: ^4.2.4
  firebase_storage: ^11.2.5
  get_it: ^7.6.0
  go_router: ^10.0.0
  injectable: ^2.1.2
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  collection: ^1.17.0
  json_serializable: ^6.7.0
  google_fonts: ^4.0.4
  shared_preferences: ^2.1.1
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.6

flutter:
  uses-material-design: true
