/// Flutter icons ClinicaIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ClinicaIcons
///      fonts:
///       - asset: fonts/ClinicaIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ClinicaIcons {
  ClinicaIcons._();

  static const _kFontFam = 'ClinicaIcons';
  static const String? _kFontPkg = null;

  static const IconData medicalRecord = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData healthiconsDoctor = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signout = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData house = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clockbaselinehistory = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userConfig = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seach = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData family = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
